#ifndef BROKER_CONFIG_H
#define BROKER_CONFIG_H

#define ICURE_MQTT_ID "ESP32-iCure"
#define ICURE_MQTT_USER "IoT_device"
#define ICURE_MQTT_PASSWORD "icureEspPassword"

#define INCOMING_COMMANDS_TOPIC "EU/BE/cmd"

#define BROKER_IP "buchinn.be"
#define BROKER_PORT 8883

static const char CA_CERT[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDqzCCApOgAwIBAgIUAJK/g3wNJsYKvwLKRes/Avx9pKswDQYJKoZIhvcNAQEL
BQAwZTELMAkGA1UEBhMCQkUxETAPBgNVBAgMCFdhbGxvbmlhMREwDwYDVQQHDAhC
cnVzc2VsczEOMAwGA1UECgwFaWN1cmUxCzAJBgNVBAsMAklUMRMwEQYDVQQDDApi
dWNoaW5uLmJlMB4XDTI0MDMxOTEwMDM1N1oXDTI1MDMxOTEwMDM1N1owZTELMAkG
A1UEBhMCQkUxETAPBgNVBAgMCFdhbGxvbmlhMREwDwYDVQQHDAhCcnVzc2VsczEO
MAwGA1UECgwFaWN1cmUxCzAJBgNVBAsMAklUMRMwEQYDVQQDDApidWNoaW5uLmJl
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxEMA8XfKWHssTfw4C6It
0tOb2phi3RYYW4OJWQqLW/6hJheqKZ2urE9454G/Y0RKKBxpzjN8pKOLy71ExrNz
c2aZpbLyWbUR08I4he1aALjPnejquf+2DriFrTB/8fHysnKGXjm9T9zEF6fNwGHI
DoL1fvwdvZuZJ7lVv+mCFb5oiBEejZOnGyzyWJntiUdb5GSm34r8MUZCdn4CD9Xi
kw5vWAR663glYTMdYnFTWM3Tau9HZBEcUz8VmiXDPhoXm8Zk58BqXigaSEIsNR58
i70j+2qozEolrB9AvcrhWIUdLYwP8Qlkbqkbx8wqPuAXcY6WHYXQbNt6fi28pxR1
tQIDAQABo1MwUTAdBgNVHQ4EFgQUcnBp6BL7SmWJ4Li5Va8LCefvXj8wHwYDVR0j
BBgwFoAUcnBp6BL7SmWJ4Li5Va8LCefvXj8wDwYDVR0TAQH/BAUwAwEB/zANBgkq
hkiG9w0BAQsFAAOCAQEAvesDGRFCqTDq6Gj9LSuLPnV2jY2V/D6hpQMgk+IB9rwA
02mDz0FO3ducVlSjOGFEWMjWzGrEkgVpPmPSJCAh+FJiJZL7ta772qmBsS2VGbhH
Nwp1slrlMo6dL66uf7BRFH+QGJaG+up7s7yan88L06c/ZLJrfUlJDJPfSAYNTTgC
TIJJ5OV2wHC+2npSQq4UwG450JBpbGehyFJby7udNugszjCZPcaHCPymsUi/G+70
fEpiLj8uoZUvFA1KOMibJz4h4J+MUGLkgs+d5IxjJJ654j8z+AMEWomV+uap9XDG
+emjOImZtystdhEYR0PP0Z9q19+pnUCFny4+QQUoAg==
-----END CERTIFICATE-----
)EOF";

// static const char CLIENT_KEY[] PROGMEM = R"EOF(

// )EOF";

// static const char CLIENT_CERT[] PROGMEM = R"EOF(
// -----BEGIN CERTIFICATE-----

// )EOF";

#endif